/**
 * William Ikenna-Nwosu (wiknwo)
 * 
 * The sequence of triangle numbers is generated by 
 * adding the natural numbers. So the 7th triangle number 
 * would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten 
 * terms would be:
 * 
 * 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
 * 
 * 1: 1
 * 3: 1,3
 * 6: 1,2,3,6
 * 10: 1,2,5,10
 * 15: 1,3,5,15
 * 21: 1,3,7,21
 * 28: 1,2,4,7,14,28
 *
 * We can see that 28 is the first triangle number to have 
 * over five divisors.
 * 
 * What is the value of the first triangle number to have 
 * over five hundred divisors?
 **/
#include <iostream>
using namespace std;

// Function prototypes
int generateTrianglularNumber(int number);
int countDivisors(int n);

// Function definitions
int generateTriangularNumber(int number){
    return number * (number + 1) / 2;
}

int countDivisors(int number){
    int divisors = 0;
    for(int i = 0;i <= number;i++){
        if(number % i == 0){
            divisors++;
        }
    }
    return divisors;
}

int main(){
    int divisors = 0;
    int triangularNumber = -1;
    int count = 1;

    while(divisors <= 500){
        triangularNumber = generateTriangularNumber(count++);
        divisors = countDivisors(triangularNumber);
    }

    cout << "The triangular number is: " << triangularNumber;
}